# API Service (External LoadBalancer)
apiVersion: v1
kind: Service
metadata:
  name: agentrun-api-service
  namespace: agentrun
  labels:
    app: agentrun
    component: api
spec:
  type: LoadBalancer
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: agentrun
    component: api
